# Generated by Django 5.1.5 on 2025-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
