# Generated by Django 5.1.5 on 2025-03-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_request_result_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='website_id',
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='products',
        ),
        migrations.DeleteModel(
            name='website_details',
        ),
    ]
