# Generated by Django 5.1.5 on 2025-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_remove_products_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_passwd', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
