# Generated by Django 5.1.6 on 2025-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_categories_website_details_products_price_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_track',
            name='desired_price',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='price_track',
            name='last_price',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='price_track',
            name='tracking_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Completed')], default=1, max_length=1),
        ),
    ]
