# Generated by Django 5.1.6 on 2025-04-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_price_track_desired_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_track',
            name='desired_price',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='price_track',
            name='last_price',
            field=models.CharField(),
        ),
    ]
