# Generated by Django 5.1.6 on 2025-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_price_track_desired_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
